{
 "title": "Crypto Exchange",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "BTC Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"BTCUSD\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"ETHUSD\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTCUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"BTCUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"BTCUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"BTCUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"BTCUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"BTCUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"BTCUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    },
    {
     "expr": "kraken_ohlc_volume{pair=\"BTCUSD\"}",
     "legendFormat": "Volume: {{label_name}}"
    }
   ]
  },
  {
   "title": "ETHUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"ETHUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"ETHUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"ETHUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"ETHUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"ETHUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"ETHUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    },
    {
     "expr": "kraken_ohlc_volume{pair=\"ETHUSD\"}",
     "legendFormat": "Volume: {{label_name}}"
    }
   ]
  },
  {
   "title": "LUNAUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"LUNAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"LUNAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"LUNAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"LUNAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"LUNAUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"LUNAUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "DOGEUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"DOGEUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"DOGEUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"DOGEUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"DOGEUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"DOGEUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"DOGEUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "SANDUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"SANDUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"SANDUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"SANDUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"SANDUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"SANDUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"SANDUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "MANAUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"MANAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"MANAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"MANAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"MANAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"MANAUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"MANAUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "STORJUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"STORJUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"STORJUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"STORJUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"STORJUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"STORJUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"STORJUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "KAVAUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"KAVAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"KAVAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"KAVAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"KAVAUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"KAVAUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"KAVAUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "ETHWUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"ETHWUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"ETHWUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"ETHWUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"ETHWUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"ETHWUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"ETHWUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  },
  {
   "title": "HNTUSD",
   "type": "candlestick",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "last_over_time(kraken_ohlc_open{pair=\"HNTUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_high{pair=\"HNTUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_low{pair=\"HNTUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "last_over_time(kraken_ohlc_close{pair=\"HNTUSD\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(kraken_ohlc_close{pair=\"HNTUSD\"}[20h])",
     "legendFormat": "MA(20): {{__value.raw}}"
    },
    {
     "expr": "kraken_ohlc_close{pair=\"HNTUSD\"}",
     "legendFormat": "Close: {{label_name}}"
    }
   ]
  }
 ]
}